# Generated by Django 2.1.15 on 2021-02-12 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE FULLTEXT INDEX `name` on core_meme(`name`);',
            reverse_sql='ALTER TABLE core_meme DROP INDEX `name`',
        ),
        migrations.RunSQL(
            sql='CREATE FULLTEXT INDEX `caption` on core_meme(`caption`);',
            reverse_sql='ALTER TABLE core_meme DROP INDEX `caption`',
        ),
        migrations.RunSQL(
            sql='CREATE FULLTEXT INDEX `url` on core_meme(`url`);',
            reverse_sql='ALTER TABLE core_meme DROP INDEX `url`',
        ),
    ]
